# Generated by Django 4.1.7 on 2023-03-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_emailid', models.EmailField(max_length=100, unique=True)),
                ('contact_sub', models.CharField(max_length=100)),
                ('contactno', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'contactus_table',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(unique=True)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registration_table',
            },
        ),
    ]
