# Generated by Django 4.1.7 on 2023-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_recruiterregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=100, unique=True)),
                ('contactno', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'enroll_table',
            },
        ),
    ]
